all: client serveur game protocol

client: client.c
	gcc -o client client.c

serveur: serveur.c
	gcc -o serveur serveur.c

game: game.c
	gcc -o game game.c

protocol: protocol.c
	gcc -o protocol protocol.c

clean:
	rm -f client serveur